### ISSUE TITLE
Topic Guide: Scopes

### ISSUE THREAD

**Issue by technosophos** [oam-dev/rudr#211]
**Warning**: As of this writing, scopes are not implemented

This guide explains how scopes work

- The existing scopes (healthcheck, network, identity)
- Creating an instance of a scope in an application configuration
- Attaching a component to a scope in an application configuration
- Best practices for when to create a new scope and how to share one scope across multiple application configurations

**Comment by wonderflow** [comment]
I think this issue could be closed as #393 was merged
