### ISSUE TITLE
Nightly Build for image is still failing

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#334]
It seems docker cli in Action doesn't support `docker manifest`:

> docker manifest create hydraoss/scylla:latest hydraoss/scylla-amd64:latest hydraoss/scylla-arm64:latest
docker manifest create is only supported on a Docker cli with experimental cli features enabled
make: *** [docker-publish] Error 1
Makefile:40: recipe for target 'docker-publish' failed
##[error]Process completed with exit code 2.

Can we use `docker tag` and `docker push` instead ? @jiria

**Comment by technosophos** [comment]
I believe this is now closed. Please re-open if the problem crops up again. And thanks @jiria !
