### ISSUE TITLE
Kuberentes Deployment to OAM converter

### ISSUE THREAD

**Issue by xiang90** [oam-dev/rudr#347]
Ideally, we can covert a given kubernetes deployment object to a OAM defined application component and the required traits. Then the users can enjoy the benefit of separate concerns and supplying orthogonal operational capabilities without changing the app definition.

/cc @wonderflow

**Comment by hongchaodeng** [comment]
Per our last weekly meeting, we will create _oam-dev/oamctl_ repo and have a _migrate_ feature.

The repo is created: https://github.com/oam-dev/oamctl

**Comment by hongchaodeng** [comment]
Let's close this and move future discussion to https://github.com/oam-dev/oamctl/issues/1
