### ISSUE TITLE
Feature: Admission controller for component and app config validation

### ISSUE THREAD

**Issue by technosophos** [oam-dev/rudr#349]
We should come up with a uniform way of gracefully failing when a component's or trait's validation fails. Right now, the status checks still run for those.

Might we be able to use admission controllers to run the validation of an AppConfig or a Component? That could provide a more robust path to error handling.

**Comment by technosophos** [comment]
On #348, @wonderflow suggested an admission controller, too. I think that is probably the direction we should go.

**Comment by xiang90** [comment]
+1 on admission controller for validation.

**Comment by technosophos** [comment]
Updated title and labels to reflect current plan

**Comment by wonderflow** [comment]
I'm working on it
