### ISSUE TITLE
Nightly build is stuck

### ISSUE THREAD

**Issue by jiria** [oam-dev/rudr#360]
The [latest nightly build](https://github.com/oam-dev/rudr/commit/3a08fa48b9b23f0d8b3da8f0f3b2ef7a27118992/checks?check_suite_id=264869850) is stuck. Since there are no logs to look at, I have contacted the Github Support. Will update when I learn more.

**Comment by technosophos** [comment]
@jiria That job had just started around the time we moved the repo from private to public. Probably we orphaned something while doing so. That might help GH folks find what is wrong.

**Comment by jiria** [comment]
Thanks, I have updated the ticket.

**Comment by wonderflow** [comment]
dup with #373 , I think we could close this. Feel free to discuss under that issue

**Comment by wonderflow** [comment]
Thanks for tracking this
