### ISSUE TITLE
Nightly build needs new creds

### ISSUE THREAD

**Issue by jiria** [oam-dev/rudr#370]
With the repos move, we are also using a new docker hub. With that, the older creds to docker hub seem to be no longer working. Can somebody who knows the new creds and has access update the creds to unblock the [nightly build](https://github.com/oam-dev/rudr/commit/e0e69e53ce11d42f9ac87541c13379950a764ad7/checks?check_suite_id=266610851).

```
docker push oamdev/rudr-amd64:latest
The push refers to repository [docker.io/oamdev/rudr-amd64]
271e75024979: Preparing
70edbbf7cc9b: Preparing
fe15497a0207: Preparing
e9dc98463cd6: Preparing
denied: requested access to the resource is denied
```

**Comment by wonderflow** [comment]
I have add hydraoss account to owners, and tested, this gonna to be OK tonight. 

Closing
