### ISSUE TITLE
Rotating meeting time for community meeting

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#374]
Now community meeting time is :  Bi-weekly (Starting Oct 22, 2019), Tuesdays 10:30AM PST, but this is 1:30 AM around in Asia.

I know only one meeting time to fit everyone could be impossible, so I suggest we could use single and double week time for community meeting. 

Then we can add a better time for Asia users.

I think choosing from 5:00PM PST ~ 5:00AM PST(+1day) will be OK, that is 8:00AM~8:00PM China Time.

**Comment by suhuruli** [comment]
Agreed with this. Let's bring this up in the next community call and discuss friendlier times.

**Comment by wonderflow** [comment]
@suhuruli  What about the meeting time now? Some Chinese developers also told us that they want to join the meeting.
