### ISSUE TITLE
Add this project to awesome rust 

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/rudr#376]
This is almost the first rust project in Kubernetes Ecosystem, It has lots referential value for users to use K8s in rust.

We could add this project to [awesome-rust](https://github.com/rust-unofficial/awesome-rust).

**Comment by ewbankkit** [comment]
Submitted https://github.com/rust-unofficial/awesome-rust/pull/745.

**Comment by ewbankkit** [comment]
@wonderflow https://github.com/rust-unofficial/awesome-rust/pull/745 has now been merged; This issue can now be closed.

**Comment by hongchaodeng** [comment]
Closing.

Thanks @ewbankkit
