### ISSUE TITLE
rudr cannot be installed by helm

### ISSUE THREAD

**Issue by kazu-1010** [oam-dev/rudr#388]
I am setting up rudr reading setup/install.md

When I try to install rudr executing

```
helm install rudr ./charts/rudr --wait --set image.tag=v1.0.0-alpha.1
```

it results in

```
Error: path "./charts/rudr" not found
```

**Comment by bacongobbler** [comment]
Are you running those instructions from the repository root?

https://github.com/oam-dev/rudr/tree/master/charts/

**Comment by kazu-1010** [comment]
Thank you @bacongobbler .

I overlooked the repository root,
and now it has been successfully installed.
