### ISSUE TITLE
Keda installation is incorrect

### ISSUE THREAD

**Issue by Haishi2016** [oam-dev/rudr#401]
Description of the issue: 

In two places in the documentation we have instructions to install KEDA that are not inline with the instructions in the KEDA docs: https://github.com/kedacore/keda. 

- https://github.com/oam-dev/rudr/blob/0d15b1c92ccbfd0ea0bc549a5f7675c25c4e61b2/docs/setup/install.md

- https://github.com/oam-dev/rudr/blob/dd0332ff6a7d27c99f385fb9c26a6f66399821c8/docs/concepts/traits.md 

Specifically, the instructions from the [KEDA setup](https://github.com/kedacore/keda#setup) need to be included.

**Comment by suhuruli** [comment]
I can take this one

**Comment by suhuruli** [comment]
Update: KEDA instructions https://hub.helm.sh/charts/kedacore/keda-edge indicate that it supports only installation with Helm 2. 

Installing with Helm 3 gives me the following error: Error: failed to download "kedacore/keda-edge" (hint: running `helm repo update` may help) despite adding the relevant repos and updating my repo.

**Comment by wonderflow** [comment]
Let me close it since the PR was merged
