### ISSUE TITLE
docs: Component Schematic concepts article misleading table

### ISSUE THREAD

**Issue by macolso** [oam-dev/rudr#406]
Under the **Container** section of the https://github.com/oam-dev/rudr/blob/master/docs/concepts/component-schematic.md#containers concept article, the resources row is not ticked as "required". This is partially misleading since some of the resources are required but not all (see [here](https://github.com/oam-dev/rudr/blob/master/docs/concepts/component-schematic.md#resources)). I think the resources row should be marked as required on the **Container** section

**Comment by macolso** [comment]
also - are parameter overrides supported in Rudr?

**Comment by suhuruli** [comment]
> also - are parameter overrides supported in Rudr?

Yes

**Comment by wonderflow** [comment]
Yeah, I think resources should be ticked as "required" now.

Some more discussion: https://github.com/oam-dev/spec/pull/218

**Comment by wonderflow** [comment]
also this is not implemented in rudr https://github.com/oam-dev/rudr/issues/277
