### ISSUE TITLE
Discussion: "Using Rudr" needs to be shorter and scenario based

### ISSUE THREAD

**Issue by macolso** [oam-dev/rudr#414]
Description of the Issue: 

- Its not immediately clear what I'm achieving here in the [Using Rudr](https://github.com/oam-dev/rudr/blob/master/docs/concepts/using_rudr.md) concept article. 

One approach to a solution:

- We could rework it to be based on a real world scenario with a clear goal.

**Comment by suhuruli** [comment]
I deleted the "In addition, the **4 concepts, 1 action** section is ambiguous as to what the 4 main concepts are." in the original issue and opened up a new issue.
