### ISSUE TITLE
docs: debugging doc?

### ISSUE THREAD

**Issue by macolso** [oam-dev/rudr#418]
There currently isn't a debugging article, which could be very helpful for "known issues" or "common blunders." For example, my component failed to deployed and I don't know where to go from here.

**Comment by iyyappam** [comment]
Yes, I got burned by this. Definitely needed for playing around with rudr.

**Comment by wonderflow** [comment]
I don't very understand what kind of instructions to give, do you need an operation docs or something else?

For example :

1. use  `kubectl logs -f <rudr-pod-name>` to see what errors happen in rudr ?
2. give issue template to tell what kind of details should be given to describe a good issue?
3. add more FAQs to tell common troubles?

**Comment by iyyappam** [comment]
Where to get the logs when the pod itself is not deployed and configuration apply is successful?
If the pod is running, then it is straight forward to get the logs.

**Comment by wonderflow** [comment]
Yeah, there could have some steps to do troubleshooting:

## get rudr pods

```
$ kubectl get pods -l app.kubernetes.io/name=rudr
NAME                    READY   STATUS    RESTARTS   AGE
rudr-6b9b9c57cd-zxgfr   1/1     Running   0          30s
```

## check rudr logs

```
$ kubectl logs -f rudr-6b9b9c57cd-zxgfr 
```

Usually if the pod of app is not deployed, there will have error information in the logs.

## pods is created by unexpected

Maybe create an issue with detail output and what expect result wanted.

Now rudr project is still very primitive, we have plan to add admission controller to validate, add kubenetes event to show error info, etc..
