### ISSUE TITLE
docs: Helm 3 instructions should tell you to add NGINX repo's 

### ISSUE THREAD

**Issue by suhuruli** [oam-dev/rudr#422]
Description of the Issue: 

- In the [Setup](https://github.com/oam-dev/rudr/blob/master/docs/setup/install.md) document, the instructions point to installing Helm 3 but once this is done, the relevant repos need to be added in order to install things like NGINX which is used in the docs for Ingress or KEDA which is used for autoscale 

Possible approaches to a solution: 
- The following [instruction](https://v3.helm.sh/docs/intro/quickstart/#initialize-a-helm-chart-repository) from the Helm 3 documentation will need to be added to the set up document at the top. In other words, add all the repos that the docs use up front in the setup. 

- Alternatively, whenever we recommend using a particular piece of tech to accomplish goals like [NGINX](https://github.com/oam-dev/rudr/blob/master/docs/setup/install.md#ingress) for Ingress or [KEDA](https://github.com/oam-dev/rudr/blob/master/docs/setup/install.md#autoscaler) for autoscaling we can include the instruction there.

**Comment by suhuruli** [comment]
> This issue is missing a description.

I added the issue description now.

**Comment by wonderflow** [comment]
closing
