### ISSUE TITLE
CLI command to get supported traits should show it per workload type 

### ISSUE THREAD

**Issue by suhuruli** [oam-dev/rudr#424]
- If you run `kubectl get traits` it shows you the list of all traits available. It would be nice if we could also see what traits are supported by specific workload types.

**Comment by wonderflow** [comment]
I think we could add this issue to [oamctl](https://github.com/oam-dev/oamctl) repo

**Comment by suhuruli** [comment]
@wonderflow, I agree, I can close it here and move it.  In fact, I just saw it is captured in the following [issue](https://github.com/oam-dev/oamctl/issues/2).
