### ISSUE TITLE
http://example2.com/ is considered a malware site

### ISSUE THREAD

**Issue by msfussell** [oam-dev/rudr#430]
Should probably choose another site.

**Comment by wonderflow** [comment]
Thanks for kindly reminding us

**Comment by suhuruli** [comment]
- The work for this issue would include updating instances in the docs that use example2.com as the `hostname` in any examples. A quick search in the docs showed the following places: 

- https://github.com/oam-dev/rudr/blob/master/docs/tutorials/deploy_and_update.md
