### ISSUE TITLE
Using Rudr documentation section is ambiguous about the 4 main concepts 

### ISSUE THREAD

**Issue by suhuruli** [oam-dev/rudr#438]
Description of the issue: 

- In the In addition, the [4 concepts, 1 action section](https://github.com/oam-dev/rudr/blob/master/docs/concepts/using_rudr.md#four-concepts-with-one-action) in the Using Rudr documentation is ambiguous as to what the 4 main concepts are. 

One approach to a solution: 

- This can be fixed along with #414 or can be fixed independently by explaining which four concepts in Kubernetes are made easier with a single action

**Comment by resouer** [comment]
I’d suggest fix this in #414 ASAP, so to make docs of rudr more user facing.

**Comment by erikadoyle** [comment]
Working on this (and #414) now...

**Comment by suhuruli** [comment]
Going to close this with the PR getting merged.
