### ISSUE TITLE
Reorganize the docs README ToC to have related concepts listed under proper hierarchy

### ISSUE THREAD

**Issue by suhuruli** [oam-dev/rudr#439]
Description of the Issue: 

- Reorganize the [Component Schematic](https://github.com/oam-dev/rudr/blob/master/docs/concepts/component-schematic.md) section so that the main Application Model constructs are grouped together (Component, Trait, Application Configuration) and then related concepts should be nested under their parent (ie workloads under Component)

**Comment by macolso** [comment]
I can open a PR for this one. I think there were a few knit issues with this
1. **Traits** is a H3 header whereas all the other OAM constructs are H2s
2. It would be helpful to have a 2-3 sentence intro under the **Concepts ** to give the user context as to what the sub-headers are

**Comment by suhuruli** [comment]
Thanks for picking it up! Can you update the issue labels when you pick it up and start working on it please.

**Comment by macolso** [comment]
I don't have permission to issue labels otherwise I would :(

**Comment by macolso** [comment]
Can we close this, @suhuruli?

**Comment by suhuruli** [comment]
Yes!

**Comment by suhuruli** [comment]
#451 closes this.
