### ISSUE TITLE
Add a GitHub Issue template 

### ISSUE THREAD

**Issue by suhuruli** [oam-dev/rudr#440]
Similar to the Helm repository, it would be nice to have an issue template. This helps users opening issues provide the right information and also helps people picking up issues have info to start working on the issue. 

For example, the Helm repository has the following template: 

Output of `helm version`:

Output of `kubectl version`:

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by suhuruli** [comment]
One possible issue template would be: 

- Current behavior: 
- Expected behavior: 
- Output of helm version:
- Output of kubectl version:
- Relevant screenshots:

**Comment by wonderflow** [comment]
Some important information related:
1. the result of `kubectl logs <rudr-pod>`  
2. oam yaml content
3. K8s resource yaml, such as `kubectl get deploy <deployment> -o yaml`
