### ISSUE TITLE
Cleanup doc issues

### ISSUE THREAD

**Issue by iyyappam** [oam-dev/rudr#476]
1. In create_component_from_scratch.md,  ComponentExample has additional field "spec.name" (with value "helloworld-python"). Need to remove it.

2. Add link at the end of create_component_from_scratch.md to "ApplicationConfiguration".

3. In install.md, update KEDA install instructions. The repo to install KEDA through Helm 3 has changed. "helm repo add kedacore https://kedacore.github.io/charts"

**Comment by iyyappam** [comment]
I'll send a PR for this.

**Comment by macolso** [comment]
here's the link to the helm3 keda install: https://keda.sh/deploy/

**Comment by iyyappam** [comment]
Keda install instruction is already fixed. We need to clean up the remaining issues. Zed will take care of it.
