### ISSUE TITLE
Use fixed schema for traits input instead of name/value pairs.

### ISSUE THREAD

**Issue by iyyappam** [oam-dev/rudr#478]
**Describe the bug**

The traits uses name/value pair to provide inputs instead of using well-known schema provided in OAM spec.

**OAM yaml files used**

      traits:
        - name: manual-scaler
          parameterValues:
            - name: replicaCount
              value: 3

**What happened**:

Input to manual scaler is name/value pair.

**What you expected to happen**:

It should follow the schema in the OAM spec and it should be in the format below

      traits:
        - name: manual-scaler
          properties:
            - replicaCount : 3

**Comment by iyyappam** [comment]
I'll take care of this.

**Comment by hongchaodeng** [comment]
fixed by https://github.com/oam-dev/rudr/pull/504
