### ISSUE TITLE
Add openAPI V3 validation schema in the componentSchematics and applicationConfiguration crds.

### ISSUE THREAD

**Issue by iyyappam** [oam-dev/rudr#484]

**Comment by resouer** [comment]
Yes, we actually just discussed about it offline. @wonderflow may have more inputs.

**Comment by wonderflow** [comment]
Is this duplicate with https://github.com/oam-dev/rudr/issues/31?

We could discuss there.

**Comment by iyyappam** [comment]
Sounds good.
