### ISSUE TITLE
./rudr: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by ./rudr)

### ISSUE THREAD

**Issue by fleeto** [oam-dev/rudr#488]
Output of helm version:

`version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}`

Output of kubectl version:

~~~
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
~~~

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

Digital Ocean

**Describe the bug**

`helm install rudr charts/rudr`

~~~command
$ kubectl logs -f -l app.kubernetes.io/name=rudr                                                             master
./rudr: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by ./rudr)
~~~

**OAM yaml files used**

N/A

**What happened**:

**What you expected to happen**:

**Relevant screenshots**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by wonderflow** [comment]
Sorry for that, I'm building image to fix this, it takes some time.

**Comment by wonderflow** [comment]
I have manually pushed image oamdev/rudr:latest (amd64), you could give a try again.

**Comment by fleeto** [comment]
Thank u It's working now.
