### ISSUE TITLE
Is instigator.rs only edge triggered?

### ISSUE THREAD

**Issue by glyn** [oam-dev/rudr#528]
Apologies for this query in the form of a bug report, but hopefully it will be easy to answer.

I skimmed through `instigator.rs` and got the impression that it was edge triggered only. Does it cope with objects existing when the controller starts up and, if so, how?

**Comment by hongchaodeng** [comment]
The current kubernetes rust client has dismissed some capabilities which exists in go client. See https://github.com/clux/kube-rs/issues/68 .

>  Does it cope with objects existing when the controller starts up

Yes.

**Comment by glyn** [comment]
Thanks. I wanted to try some experiments, but I can't run with GKE and macOS until kube is upgraded. Closing for now.

**Comment by glyn** [comment]
Raised https://github.com/oam-dev/rudr/issues/529
