### ISSUE TITLE
prometheusapp.yaml error

### ISSUE THREAD

**Issue by allenhaozi** [oam-dev/rudr#535]
Output of helm version:
v3.0.3
Output of kubectl version:
v1.17.0
Cloud Provider/Platform (AKS, GKE, Minikube etc.):
minikube version: v1.6.2

**Describe the bug**
kubectl apply -f examples/prometheusapp.yaml
```
The ComponentSchematic "prometheus" is invalid: spec.workloadSettings: Invalid value: "array": spec.workloadSettings in body must be of type object: "array"
```
debug log
```
 DEBUG [kube::client:/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/kube-0.16.1/src/client/mod.rs:179] Unsuccessful: ApiError { status: "Failure", message: "prometheuses.monitoring.coreos.com is forbidden: User \"system:serviceaccount:default:rudr\" cannot create resource \"prometheuses\" in API group \"monitoring.coreos.com\" in the namespace \"default\"", reason: "Forbidden", code: 403 }
2020-02-06 04:01:16 ERROR [rudr:src/main.rs:129] Error processing event: Error { inner: 

ApiError Forbidden ("prometheuses.monitoring.coreos.com is forbidden: User \"system:serviceaccount:default:rudr\" cannot create resource \"prometheuses\" in API group \"monitoring.coreos.com\" in the namespace \"default\"") }
```
**OAM yaml files used**

**What happened**:

**What you expected to happen**:

**Relevant screenshots**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by wonderflow** [comment]
The `ComponentSchematic` CRD in Rudr didn't have this constraint, maybe you're using oam-go-sdk ?

We're going to do that change though.
