### ISSUE TITLE
Better clarification on Rudr/Knative differences

### ISSUE THREAD

**Issue by yaron2** [oam-dev/rudr#541]
The answer [here](https://github.com/oam-dev/rudr/blob/master/docs/faq.md#how-does-this-compare-to-knative) should provide more details, for example what is the problem space that the two technologies are addressing, and where do they overlap if at all.

**Comment by resouer** [comment]
FYI, it's partially answered in https://github.com/oam-dev/rudr/issues/534

**Comment by yaron2** [comment]
> FYI, it's partially answered in #534

Yes, better if it makes its way to the FAQ.
