### ISSUE TITLE
Support TLS in Rudr Ingress Trait

### ISSUE THREAD

**Issue by alissonsol** [oam-dev/rudr#553]
TLS in the Ingress trait is currently not supported in Rudr. This is a need for deployment one of our projects.

Code that creates the Ingress in K8S is at:
https://github.com/oam-dev/rudr/blob/master/src/schematic/traits/ingress.rs

**Comment by artursouza** [comment]
Please, assign this issue to me and close it once PR is merged.

**Comment by wonderflow** [comment]
@artursouza  merged, thanks!
