### ISSUE TITLE
All the paragraph end with a full stop `.`, maybe there should also be one.

### ISSUE THREAD

**Issue by ji0230** [oam-dev/rudr#560]
A little Docs type thing I run into when reading, maybe a full stop `.` is better.
![image](https://user-images.githubusercontent.com/7296910/85876229-fc931180-b807-11ea-9059-93a3ecd993bb.png)

**Comment by ryanzhang-oss** [comment]
Thanks, please submit a PR

**Comment by ji0230** [comment]
@ryanzhang-oss The PR is submitted here: https://github.com/oam-dev/rudr/pull/561.
