### ISSUE TITLE
Add StatefulService Workload

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/rudr#75]
Currently, we have ReplicatedService which provides good support for stateless workload and actually based on k8s deployment. For our use case, we want to support existing stateful workload that already runs on k8s StatefulSet on Scylla. Adding this StatefulService workload abstraction would be necessary for more adoption, and could further benefits the community.

**Comment by wonderflow** [comment]
Now we implement Singleton Server and Singleton Worker using StatefulSet of K8s

**Comment by wonderflow** [comment]
Closing as we have implemented Singleton Server and Singleton Worker using StatefulSet of K8s
